### ISSUE TITLE
Error when someone  DMs are not open

### ISSUE THREAD

**Issue by HexPandaa** [HexPandaa/ensimag-alternance-pointage#1]
When someone who's DMs are not open react to an event, the bot fails to send him a message (obviously), but consequently does not execute the next instructions.

```
Task exception was never retrieved
future: <Task finished coro=<CalendarCog.check_in() done, defined at /xxx/ensimag-alternance-pointage/cogs/calendar.py:115> exception=Forbidden('403 Forbidden (error code: 50007): Cannot send messages to this user')>
Traceback (most recent call last):
  File "/xxx/ensimag-alternance-pointage/cogs/calendar.py", line 135, in check_in
    await self.send_check_in_status(status, course, user)
  File "/xxx/ensimag-alternance-pointage/cogs/calendar.py", line 142, in send_check_in_status
    await user.send(f":white_check_mark: Pointage pour le cours de {course['name']} réussi !")
  File "/xxx/.local/lib/python3.7/site-packages/discord/abc.py", line 937, in send
    message_reference=reference)
  File "/xxx/.local/lib/python3.7/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
```

**Comment by HexPandaa** [comment]
Fixed in https://github.com/HexPandaa/ensimag-alternance-pointage/commit/0c110209350b6fc3c4459e38eb6c3b28e6dca5f5
